name: ClawdClient
options:
  bundleIdPrefix: com.clawd
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  ClawdClient-macOS:
    type: application
    platform: macOS
    sources:
      - path: ClawdClient/Shared
      - path: ClawdClient/macOS
      - path: ClawdClient/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clawd.client.macos
        PRODUCT_NAME: Clawd
        INFOPLIST_FILE: ClawdClient/macOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: ClawdClient/macOS/ClawdClient.entitlements
    entitlements:
      path: ClawdClient/macOS/ClawdClient.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.device.audio-input: true
  
  ClawdClient-iOS:
    type: application
    platform: iOS
    sources:
      - path: ClawdClient/Shared
      - path: ClawdClient/iOS
      - path: ClawdClient/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clawd.client.ios
        PRODUCT_NAME: Clawd
        INFOPLIST_FILE: ClawdClient/iOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    info:
      path: ClawdClient/iOS/Info.plist
      properties:
        UILaunchScreen: {}
        NSMicrophoneUsageDescription: "Clawd needs microphone access for voice messages"
        NSPhotoLibraryUsageDescription: "Clawd needs photo library access to attach images"
        NSCameraUsageDescription: "Clawd needs camera access to take photos"

schemes:
  ClawdClient-macOS:
    build:
      targets:
        ClawdClient-macOS: all
    run:
      config: Debug
  
  ClawdClient-iOS:
    build:
      targets:
        ClawdClient-iOS: all
    run:
      config: Debug
